# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6f3e05a3-0175-4517-8e4e-a83decc50528";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4e8c8e40-70fd-4037-bfb6-301bcf63f9e1".device = "/dev/disk/by-uuid/4e8c8e40-70fd-4037-bfb6-301bcf63f9e1";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/46A3-A33C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ 
      {
        device = "/dev/disk/by-uuid/02e07d18-573e-43ca-a6ba-acffb6032c17"; 
        encrypted = {
          enable = true;
          blkDev = "/dev/disk/by-uuid/087f86ba-ec71-40f5-8e55-ffef7e419168";
          label = "swap";
        };
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wwan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
